### ISSUE TITLE
Add Strava Heatmap

### ISSUE THREAD

**Issue by nnngrach** [nnngrach/AnyGIS_maps#2]

**Comment by JBuitelaar** [comment]
This works great! would it be possible to also create a version for the "red" heatmap? In the strava url, it just replaces "hot" with "bluered".
The advantage of the red one is that it doesn't show the parts with really low density, making it less cluttered (and only showing the most relevant information)

**Comment by nnngrach** [comment]
I added a new map to the site in the Overlay section. Check these files.

**Comment by JBuitelaar** [comment]
Works perfectly, thank you very much!
